version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_app
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YcYWuYAOlg5m

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
